----CREATE DATABASE studentska_sluzba;
----Mogu se kreirati i u istom queryju kao i baza koristeci studentska_sluzba.dbo.imetabele
CREATE TABLE Predmet(

	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NAZIV NVARCHAR(255) NOT NULL,
	ESPB INT NOT NULL

);

CREATE TABLE Zvanje(

	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NAZIV NVARCHAR(30) NOT NULL,

);

CREATE TABLE Nastavnik(

	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	IME NVARCHAR(100) NOT NULL,
	PREZIME NVARCHAR(100) NOT NULL,
	ZVANJE_ID INT NOT NULL FOREIGN KEY REFERENCES Zvanje(ID)

);

INSERT INTO PREDMET(NAZIV,ESPB) VALUES ('Matematika 1',6);
INSERT INTO PREDMET(NAZIV,ESPB) VALUES ('Statistika',6);
INSERT INTO PREDMET(NAZIV,ESPB) VALUES ('Elektronsko Poslovanje',5);
INSERT INTO PREDMET(NAZIV,ESPB) VALUES ('Programiranje 1',6);
INSERT INTO PREDMET(NAZIV,ESPB) VALUES ('Engleski 1',3);
INSERT INTO PREDMET(NAZIV,ESPB) VALUES ('Engleski 2',3);
INSERT INTO PREDMET(NAZIV,ESPB) VALUES ('Programiranje 2',6);
INSERT INTO PREDMET(NAZIV,ESPB) VALUES ('Matematika 2',6);
INSERT INTO PREDMET(NAZIV,ESPB) VALUES ('Matematika 3',6);
INSERT INTO PREDMET(NAZIV,ESPB) VALUES ('Mobilno Poslovanje',4);

INSERT INTO ZVANJE VALUES('Asistent');
INSERT INTO ZVANJE VALUES('Asistent sa doktoratom');
INSERT INTO ZVANJE VALUES('Docent');
INSERT INTO ZVANJE VALUES('Vanredni Profesor');
INSERT INTO ZVANJE VALUES('Redovni Profesor');

INSERT INTO NASTAVNIK(IME,PREZIME,ZVANJE_ID) VALUES('Dejan','Simić',5);
INSERT INTO NASTAVNIK(IME,PREZIME,ZVANJE_ID) VALUES('Zoran','Radojičić',5);
INSERT INTO NASTAVNIK(IME,PREZIME,ZVANJE_ID) VALUES('Vesna','Manojlović-Todorčević',5);
INSERT INTO NASTAVNIK(IME,PREZIME,ZVANJE_ID) VALUES('Nebojša','Nikolić',4);
INSERT INTO NASTAVNIK(IME,PREZIME,ZVANJE_ID) VALUES('Aleksandar','Đoković',4);
INSERT INTO NASTAVNIK(IME,PREZIME,ZVANJE_ID) VALUES('Dušan','Savić',4);
INSERT INTO NASTAVNIK(IME,PREZIME,ZVANJE_ID) VALUES('Danijela','Toljaga-Nikolić',3);
INSERT INTO NASTAVNIK(IME,PREZIME,ZVANJE_ID) VALUES('Ivan','Milenković',3);
INSERT INTO NASTAVNIK(IME,PREZIME,ZVANJE_ID) VALUES('Milan','Radojičić',3);
INSERT INTO NASTAVNIK(IME,PREZIME,ZVANJE_ID) VALUES('Tatjana','Stojanović',2);
INSERT INTO NASTAVNIK(IME,PREZIME,ZVANJE_ID) VALUES('Tatjana','Bailović',2);
INSERT INTO NASTAVNIK(IME,PREZIME,ZVANJE_ID) VALUES('Miloš','Milić',2);
INSERT INTO NASTAVNIK(IME,PREZIME,ZVANJE_ID) VALUES('Ivona','Jovanović',1);
INSERT INTO NASTAVNIK(IME,PREZIME,ZVANJE_ID) VALUES('Milica','Škembarević',1);
INSERT INTO NASTAVNIK(IME,PREZIME,ZVANJE_ID) VALUES('Tamara','Naumović',1);
